CREATE TABLE `DbGroup` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'DB군',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);
  
CREATE TABLE `CommItem` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '상용제품',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);
  
CREATE TABLE `Maker` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '제조업체',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);
  
CREATE TABLE `CollectTime` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '채취시기',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);
  
CREATE TABLE `Ref` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '성분표출처',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);
  
CREATE TABLE `Issue` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '발행기관',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);

CREATE TABLE `FoodCate` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '식품대분류',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);
  
CREATE TABLE `FoodSubCate` (
  `id` tinyint unsigned NOT NULL AUTO_INCREMENT,
  `pid` tinyint unsigned NOT NULL COMMENT '식품대분류',
  `name` varchar(45) NOT NULL COMMENT '식품상세분류',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  KEY `ref_FoodCate_idx` (`pid`),
  CONSTRAINT `ref_FoodCate` FOREIGN KEY (`pid`) REFERENCES `FoodCate` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `Nutrition` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '번호',
  `sample_id` varchar(45) NOT NULL COMMENT '샘플아이디',
  `food_cd` varchar(45) NOT NULL COMMENT '식품코드',
  `db_group` tinyint unsigned NOT NULL COMMENT 'DB군',
  `commercial_products` tinyint unsigned NOT NULL COMMENT '상용제품',
  `food_name` varchar(45) NOT NULL COMMENT '식품이름',
  `research_year` varchar(4) NOT NULL COMMENT '조사년도',
  `maker` tinyint unsigned NOT NULL COMMENT '지역/제조사',
  `collection_timing` tinyint unsigned NOT NULL COMMENT '채취시기',
  `food_cate` tinyint unsigned NOT NULL COMMENT '식품군(대분류)',
  `food_subcate` tinyint unsigned NOT NULL COMMENT '식품상세분류',
  `serving_size` int unsigned NOT NULL COMMENT '1회 제공량',
  `capacity_unit` varchar(2) NOT NULL COMMENT '내용량 단위',
  `total_g` varchar(10) DEFAULT NULL COMMENT '총내용량(g)',
  `total_mL` varchar(10) DEFAULT NULL COMMENT '총내용량(mL)',
  `calorie` varchar(10) DEFAULT NULL COMMENT '열량(kcal)(1회제공량당)',
  `moisture` varchar(10) DEFAULT NULL COMMENT '수분(g)',
  `protein` varchar(10) DEFAULT NULL COMMENT '단백질(g)(1회제공량당)',
  `province` varchar(10) DEFAULT NULL COMMENT '지방(g)(1회제공량당)',
  `carbohydrate` varchar(10) DEFAULT NULL COMMENT '탄수화물(g)(1회제공량당)',
  `sugars` varchar(10) DEFAULT NULL COMMENT '총당류(g)(1회제공량당)',
  `sucrose` varchar(10) DEFAULT NULL COMMENT '자당(g)',
  `glucose` varchar(10) DEFAULT NULL COMMENT '포도당(g)',
  `fruit_sugar` varchar(10) DEFAULT NULL COMMENT '과당(g)',
  `lactose` varchar(10) DEFAULT NULL COMMENT '유당(g)',
  `maltose` varchar(10) DEFAULT NULL COMMENT '맥아당(g)',
  `dietary_fiber` varchar(10) DEFAULT NULL COMMENT '총 식이섬유(g)',
  `calcium` varchar(10) DEFAULT NULL COMMENT '칼슘(mg)',
  `iron_mg` varchar(10) DEFAULT NULL COMMENT '철(mg)',
  `iron_ug` varchar(10) DEFAULT NULL COMMENT '철(ug)',
  `magnesium` varchar(10) DEFAULT NULL COMMENT '마그네슘(mg)',
  `phosphorus` varchar(10) DEFAULT NULL COMMENT '인(mg)',
  `potassium` varchar(10) DEFAULT NULL COMMENT '칼륨(mg)',
  `salt` varchar(10) DEFAULT NULL COMMENT '나트륨(mg)(1회제공량당)',
  `zinc` varchar(10) DEFAULT NULL COMMENT '아연(mg)',
  `copper` varchar(10) DEFAULT NULL COMMENT '구리(mg)',
  `manganese` varchar(10) DEFAULT NULL COMMENT '망간(mg)',
  `selenium` varchar(10) DEFAULT NULL COMMENT '셀레늄(ug)',
  `retinol` varchar(10) DEFAULT NULL COMMENT '레티놀(ug)',
  `beta_carotene` varchar(10) DEFAULT NULL COMMENT '베타카로틴(ug)',
  `vitamin_D3` varchar(10) DEFAULT NULL COMMENT '비타민 D3(ug)',
  `tocophenol` varchar(10) DEFAULT NULL COMMENT '토코페롤(mg)',
  `tocotrienol` varchar(10) DEFAULT NULL COMMENT '토코트리에놀(mg)',
  `vitamin_B1` varchar(10) DEFAULT NULL COMMENT '비타민 B1(mg)',
  `vitamin_B2` varchar(10) DEFAULT NULL COMMENT '비타민 B2(mg)',
  `niacin` varchar(10) DEFAULT NULL COMMENT '나이아신(mg)',
  `folic_acid` varchar(10) DEFAULT NULL COMMENT '엽산(DFE)(ug)',
  `vitamin_B12` varchar(10) DEFAULT NULL COMMENT '비타민 B12(ug)',
  `vitamin_C` varchar(10) DEFAULT NULL COMMENT '비타민 C(mg)',
  `amino_acids` varchar(10) DEFAULT NULL COMMENT '총 아미노산(mg)',
  `isoleucine` varchar(10) DEFAULT NULL COMMENT '이소류신(mg)',
  `leucine` varchar(10) DEFAULT NULL COMMENT '류신(mg)',
  `lysine` varchar(10) DEFAULT NULL COMMENT '라이신(mg)',
  `methionine` varchar(10) DEFAULT NULL COMMENT '메티오닌(mg)',
  `phenylalanine` varchar(10) DEFAULT NULL COMMENT '페닐알라닌(mg)',
  `threonine` varchar(10) DEFAULT NULL COMMENT '트레오닌(mg)',
  `valine` varchar(10) DEFAULT NULL COMMENT '발린(mg)',
  `histidine` varchar(10) DEFAULT NULL COMMENT '히스티딘(mg)',
  `arginine` varchar(10) DEFAULT NULL COMMENT '아르기닌(mg)',
  `tyrosine` varchar(10) DEFAULT NULL COMMENT '티로신(mg)',
  `cysteine` varchar(10) DEFAULT NULL COMMENT '시스테인(mg)',
  `alanine` varchar(10) DEFAULT NULL COMMENT '알라닌(mg)',
  `aspartic_acid` varchar(10) DEFAULT NULL COMMENT '아스파르트산(mg)',
  `glutamic_acid` varchar(10) DEFAULT NULL COMMENT '글루탐산(mg)',
  `glycine` varchar(10) DEFAULT NULL COMMENT '글리신(mg)',
  `proline` varchar(10) DEFAULT NULL COMMENT '프롤린(mg)',
  `serine` varchar(10) DEFAULT NULL COMMENT '세린(mg)',
  `cholesterol` varchar(10) DEFAULT NULL COMMENT '콜레스테롤(mg)(1회제공량당)',
  `saturated_fatty_acids` varchar(10) DEFAULT NULL COMMENT '포화지방산(g)(1회제공량당)',
  `butyric_acid` varchar(10) DEFAULT NULL COMMENT '부르티산(4:0)(g)',
  `caproic_acid` varchar(10) DEFAULT NULL COMMENT '카프로산(6:0)(g)',
  `caprylic_acid` varchar(10) DEFAULT NULL COMMENT '카프릴산(8:0)(g)',
  `capric_acid` varchar(10) DEFAULT NULL COMMENT '카프르산(10:0)(g)',
  `lauric_acid` varchar(10) DEFAULT NULL COMMENT '라우르산(12:0)(g)',
  `myristic_acid` varchar(10) DEFAULT NULL COMMENT '미리스트산(14:0)(g)',
  `palmitic_acid` varchar(10) DEFAULT NULL COMMENT '팔미트산(16:0)(g)',
  `stearic_acid` varchar(10) DEFAULT NULL COMMENT '스테아르산(18:0)(g)',
  `arachidic_acid` varchar(10) DEFAULT NULL COMMENT '아라키드산(20:0)(g)',
  `myristoleic_acid` varchar(10) DEFAULT NULL COMMENT '미리스톨레산(14:1)(g)',
  `palmitoleic_acid` varchar(10) DEFAULT NULL COMMENT '팔미톨레산(16:1)(g)',
  `oleic_acid` varchar(10) DEFAULT NULL COMMENT '올레산(18:1(n-9))(g)',
  `bacsenic_acid` varchar(10) DEFAULT NULL COMMENT '박센산(18:1(n-7))(g)',
  `gadoleic_acid` varchar(10) DEFAULT NULL COMMENT '가돌레산(20:1)(g)',
  `linoleic_acid` varchar(10) DEFAULT NULL COMMENT '리놀레산(18:2(n-6)c)(g)',
  `alpha_linolenic_acid` varchar(10) DEFAULT NULL COMMENT '알파 리놀렌산(18:3(n-3))(g)',
  `gamma_linolenic_acid` varchar(10) DEFAULT NULL COMMENT '감마 리놀렌산(18:3(n-6))(g)',
  `eicosadienoic_acid` varchar(10) DEFAULT NULL COMMENT '에이코사디에노산(20:2(n-6))(g)',
  `arachidonic_acid` varchar(10) DEFAULT NULL COMMENT '아라키돈(20:4(n-6))(g)',
  `eicosatrienoic_acid` varchar(10) DEFAULT NULL COMMENT '에이코사트리에노산(20:3(n-6))(g)',
  `eicosapentaenoic_acid` varchar(10) DEFAULT NULL COMMENT '에이코사펜타에노산(20:5(n-3))(g)',
  `docosapentaenoic_acid` varchar(10) DEFAULT NULL COMMENT '도코사펜타에노산(22:5(n-3))(g)',
  `docosahexaenoic_acid` varchar(10) DEFAULT NULL COMMENT '도코사헥사에노산(22:6(n-3))(g)',
  `trans_fat` varchar(10) DEFAULT NULL COMMENT '트랜스지방(g)(1회제공량당)',
  `trans_oleic_acid` varchar(10) DEFAULT NULL COMMENT '트랜스 올레산(18:1(n-9)t)(g)',
  `trans_linoleic_acid_2t` varchar(10) DEFAULT NULL COMMENT '트랜스 리놀레산(18:2t)(g)',
  `trans_linolenic_acid_3t` varchar(10) DEFAULT NULL COMMENT '트랜스 리놀레산(18:3t)(g)',
  `ash` varchar(10) DEFAULT NULL COMMENT '회분(g)',
  `caffeine` varchar(10) DEFAULT NULL COMMENT '카페인(mg)',
  `ref` tinyint unsigned NOT NULL COMMENT '자료출처',
  `issue` tinyint unsigned NOT NULL COMMENT '발행기관',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7684 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;